#!/usr/bin/env python3
"""
WO-2026-0206-014: approved 항목 전체 정합성 복구

작업 태그: reconciled_wo014_full_approved_fix

실행:
    python reconcile_all_approved.py --scan        # 스캔만 (현황 파악)
    python reconcile_all_approved.py --dry-run     # 테스트 모드
    python reconcile_all_approved.py               # 실제 실행
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import gspread
from google.oauth2.service_account import Credentials

# Cloudinary 설정
try:
    import cloudinary
    import cloudinary.uploader
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / ".env")

    cloudinary.config(
        cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
        api_key=os.getenv("CLOUDINARY_API_KEY"),
        api_secret=os.getenv("CLOUDINARY_API_SECRET")
    )
    CLOUDINARY_AVAILABLE = True
except ImportError:
    CLOUDINARY_AVAILABLE = False

# 열 인덱스 (1-based)
COL_NUM = 1
COL_ENG_NAME = 2
COL_KR_NAME = 3
COL_SAFETY = 5        # E열: 안전도
COL_STATUS = 6        # F열: 게시상태
COL_CAPTION_INSTA = 16   # P열
COL_CAPTION_THREADS = 17  # Q열
COL_METADATA = 18     # R열
COL_CLOUDINARY = 19   # S열
COL_FOLDER_STATUS = 21  # U열

# 안전도 정의
SAFETY_LEVELS = {
    'SAFE': ['boiled_egg', 'spinach', 'chicken', 'chicken_breast', 'rice', 'cucumber',
             'carrot', 'sweet_potato', 'apple', 'banana', 'watermelon', 'blueberry',
             'pumpkin', 'broccoli', 'lettuce', 'peas', 'green_beans', 'cabbage',
             'asparagus', 'beet', 'tofu', 'white_fish', 'duck', 'turkey'],
    'CAUTION': ['shrimp', 'potato', 'nuts', 'almonds', 'cheese', 'yogurt', 'milk',
                'egg', 'peanut', 'soy', 'wheat', 'corn', 'mushroom', 'toast',
                'baguette', 'sandwich', 'croissant', 'muffin', 'pancake', 'waffle',
                'cereal', 'granola', 'bacon', 'meatball', 'chicken_skewer',
                'dakgangjeong', 'bulgogi', 'kimbap', 'bibimbap', 'udon', 'kalguksu',
                'naengmyeon', 'tteokguk', 'kimchi', 'quail_egg', 'mackerel',
                'melon', 'plum', 'pomegranate', 'raspberry', 'blackberry', 'coconut',
                'lemon', 'bean_sprouts', 'poached_egg', 'raisin', 'perrier'],
    'DANGER': ['cheetos', 'doritos', 'lays', 'ritz', 'pizza', 'ramen', 'cake',
               'brownie', 'ice_cream', 'candy', 'cookie', 'fanta', 'sprite',
               'coca_cola', 'milkis', 'banana_milk', 'reeses', 'skittles',
               'starburst', 'jjajangmyeon', 'donut', 'soju'],
    'FORBIDDEN': ['onion', 'garlic', 'grape', 'chocolate', 'xylitol', 'avocado',
                  'macadamia', 'alcohol', 'coffee', 'tea']
}


def get_safety_level(eng_name: str) -> str:
    """영문명으로 안전도 결정"""
    eng_lower = eng_name.lower()
    for level, foods in SAFETY_LEVELS.items():
        if eng_lower in [f.lower() for f in foods]:
            return level
    return 'CAUTION'  # 기본값


def get_sheet():
    """구글시트 연결"""
    scopes = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive"
    ]
    creds_path = PROJECT_ROOT / "config" / "google-credentials.json"
    creds = Credentials.from_service_account_file(str(creds_path), scopes=scopes)
    client = gspread.authorize(creds)
    return client.open("Sunshine").worksheet("게시콘텐츠")


def get_approved_folder(num: str) -> Path:
    """번호로 3_approved 폴더 찾기"""
    approved_dir = PROJECT_ROOT / "contents" / "3_approved"
    for folder in approved_dir.iterdir():
        if folder.is_dir() and folder.name.startswith(f"{num}_"):
            return folder
    return None


def generate_caption_instagram(food_kr: str, food_en: str, safety: str) -> str:
    """인스타그램 캡션 생성"""
    safety_msg = {
        'SAFE': f"🟢 {food_kr}, 강아지가 먹어도 안전해요!",
        'CAUTION': f"🟡 {food_kr}, 소량만 급여하세요!",
        'DANGER': f"🔴 {food_kr}, 급여를 권장하지 않아요!",
        'FORBIDDEN': f"⛔ {food_kr}, 절대 급여 금지!"
    }

    caption = f"""🐕 강아지 {food_kr} 먹어도 될까요?

{safety_msg.get(safety, safety_msg['CAUTION'])}

자세한 내용은 슬라이드를 확인하세요 👉

💾 저장해두고 필요할 때 확인하세요!
💬 궁금한 음식이 있다면 댓글로 알려주세요!

#강아지음식 #반려견 #강아지간식 #펫푸드 #sunshinedogfood

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI."""

    return caption


def generate_caption_threads(food_kr: str, food_en: str, safety: str) -> str:
    """쓰레드 캡션 생성"""
    safety_emoji = {'SAFE': '🟢', 'CAUTION': '🟡', 'DANGER': '🔴', 'FORBIDDEN': '⛔'}

    caption = f"""{safety_emoji.get(safety, '🟡')} 강아지 {food_kr} 먹어도 될까요?

자세한 내용은 인스타그램에서 확인하세요!
@sunshinedogfood

#강아지음식 #반려견"""

    return caption


def ensure_metadata(folder: Path, eng_name: str, kr_name: str, safety: str, dry_run=False) -> dict:
    """메타데이터 확인/생성/보완"""
    metadata_path = folder / "metadata.json"

    if metadata_path.exists():
        with open(metadata_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = {}

    changes = []

    # 필수 항목 보완
    if not data.get('food_name_en'):
        data['food_name_en'] = eng_name
        changes.append(f"food_name_en: {eng_name}")

    if not data.get('food_name_kr'):
        data['food_name_kr'] = kr_name
        changes.append(f"food_name_kr: {kr_name}")

    if not data.get('safety_level'):
        data['safety_level'] = safety
        changes.append(f"safety_level: {safety}")
    elif data.get('safety_level', '').upper() != safety:
        old = data.get('safety_level')
        data['safety_level'] = safety
        changes.append(f"safety_level: {old} → {safety}")

    if data.get('status') != 'approved':
        old = data.get('status', 'unknown')
        data['status'] = 'approved'
        changes.append(f"status: {old} → approved")

    # 정합성 복구 태그
    data['reconcile_tag'] = 'reconciled_wo014_full_approved_fix'
    data['reconciled_at'] = datetime.now().isoformat()

    if changes and not dry_run:
        with open(metadata_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    return {'changes': changes, 'path': str(metadata_path)}


def ensure_captions(folder: Path, eng_name: str, kr_name: str, safety: str, dry_run=False) -> dict:
    """캡션 파일 확인/생성"""
    result = {'instagram': False, 'threads': False, 'created': []}

    insta_path = folder / "caption_instagram.txt"
    threads_path = folder / "caption_threads.txt"

    if not insta_path.exists():
        caption = generate_caption_instagram(kr_name, eng_name, safety)
        if not dry_run:
            with open(insta_path, 'w', encoding='utf-8') as f:
                f.write(caption)
        result['created'].append('caption_instagram.txt')
    result['instagram'] = True

    if not threads_path.exists():
        caption = generate_caption_threads(kr_name, eng_name, safety)
        if not dry_run:
            with open(threads_path, 'w', encoding='utf-8') as f:
                f.write(caption)
        result['created'].append('caption_threads.txt')
    result['threads'] = True

    return result


def upload_to_cloudinary(folder: Path, num: str, eng_name: str, dry_run=False) -> dict:
    """Cloudinary 업로드"""
    if not CLOUDINARY_AVAILABLE:
        return {'success': False, 'error': 'cloudinary not available'}

    images = []
    for i in range(7):
        pattern = f"*_{i:02d}.png"
        matches = list(folder.glob(pattern))
        if matches:
            images.append(matches[0])

    if not images:
        return {'success': False, 'error': 'no images found'}

    results = []
    errors = []

    for img_path in images:
        public_id = f"sunshine/{num}_{eng_name}/{img_path.stem}"

        if dry_run:
            results.append({'file': img_path.name, 'public_id': public_id})
            continue

        try:
            result = cloudinary.uploader.upload(
                str(img_path),
                public_id=public_id,
                overwrite=True,
                resource_type="image"
            )
            results.append({
                'file': img_path.name,
                'public_id': public_id,
                'url': result.get('secure_url')
            })
        except Exception as e:
            errors.append(f"{img_path.name}: {str(e)}")

    if errors:
        return {'success': False, 'error': '; '.join(errors), 'uploaded': results}

    return {'success': True, 'uploaded': results, 'count': len(results)}


def reconcile_all(dry_run=False, scan_only=False):
    """전체 approved 항목 정합성 복구"""
    print("=" * 70)
    print(f"🔧 WO-2026-0206-014: approved 항목 전체 정합성 복구")
    print(f"   태그: reconciled_wo014_full_approved_fix")
    print(f"   시각: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    if scan_only:
        print("   모드: 스캔만 (현황 파악)")
    elif dry_run:
        print("   모드: dry-run (테스트)")
    print("=" * 70)

    sheet = get_sheet()
    all_data = sheet.get_all_values()

    # approved + P/Q/R/S 미완료 항목 찾기
    incomplete = []
    for idx, row in enumerate(all_data[1:], start=2):
        if len(row) < COL_CLOUDINARY:
            continue

        num = row[COL_NUM - 1]
        eng = row[COL_ENG_NAME - 1]
        kr = row[COL_KR_NAME - 1] if len(row) >= COL_KR_NAME else ""
        status = row[COL_STATUS - 1]
        safety = row[COL_SAFETY - 1] if len(row) >= COL_SAFETY else ""
        p = row[COL_CAPTION_INSTA - 1] if len(row) >= COL_CAPTION_INSTA else ""
        q = row[COL_CAPTION_THREADS - 1] if len(row) >= COL_CAPTION_THREADS else ""
        r = row[COL_METADATA - 1] if len(row) >= COL_METADATA else ""
        s = row[COL_CLOUDINARY - 1] if len(row) >= COL_CLOUDINARY else ""

        if status == 'approved':
            needs_fix = (p in ['-', ''] or q in ['-', ''] or
                        r in ['-', ''] or s in ['-', ''])
            if needs_fix:
                incomplete.append({
                    'idx': idx,
                    'num': num,
                    'eng': eng,
                    'kr': kr,
                    'safety': safety,
                    'p': p, 'q': q, 'r': r, 's': s
                })

    print(f"\n📊 스캔 결과: {len(incomplete)}건 정합성 복구 필요")

    if scan_only:
        print("\n번호 | 영문명 | P | Q | R | S")
        print("-" * 60)
        for item in incomplete[:20]:
            print(f"{item['num']} | {item['eng'][:15]:15} | {item['p']:4} | {item['q']:4} | {item['r']:4} | {item['s']:4}")
        if len(incomplete) > 20:
            print(f"... 외 {len(incomplete) - 20}건")
        return

    # 복구 실행
    updates = []
    stats = {
        'caption_created': 0,
        'metadata_fixed': 0,
        'cloudinary_uploaded': 0,
        'errors': []
    }

    for item in incomplete:
        num = item['num']
        eng = item['eng']
        kr = item['kr'] or eng  # 한글명 없으면 영문명 사용

        print(f"\n{'─'*60}")
        print(f"[{num}] {eng} ({kr})")

        folder = get_approved_folder(num)
        if not folder:
            print(f"  ⚠️ 폴더 없음 - 건너뜀")
            stats['errors'].append(f"{num}: folder not found")
            continue

        # 안전도 결정
        safety = get_safety_level(eng)
        print(f"  안전도: {safety}")

        # 1. 메타데이터
        if item['r'] in ['-', '']:
            print(f"  📝 메타데이터 보완...")
            meta_result = ensure_metadata(folder, eng, kr, safety, dry_run)
            if meta_result['changes']:
                for c in meta_result['changes']:
                    print(f"     - {c}")
                stats['metadata_fixed'] += 1
            updates.append({'row': item['idx'], 'col': COL_METADATA, 'val': '완료'})

        # 2. 캡션
        if item['p'] in ['-', ''] or item['q'] in ['-', '']:
            print(f"  📝 캡션 생성...")
            caption_result = ensure_captions(folder, eng, kr, safety, dry_run)
            if caption_result['created']:
                for c in caption_result['created']:
                    print(f"     - {c} 생성")
                stats['caption_created'] += 1
            if item['p'] in ['-', '']:
                updates.append({'row': item['idx'], 'col': COL_CAPTION_INSTA, 'val': '완료'})
            if item['q'] in ['-', '']:
                updates.append({'row': item['idx'], 'col': COL_CAPTION_THREADS, 'val': '완료'})

        # 3. Cloudinary
        if item['s'] in ['-', '']:
            print(f"  ☁️ Cloudinary 업로드...")
            cloud_result = upload_to_cloudinary(folder, num, eng, dry_run)
            if cloud_result['success'] or dry_run:
                print(f"     - {cloud_result.get('count', '?')}개 이미지 업로드")
                stats['cloudinary_uploaded'] += 1
                updates.append({'row': item['idx'], 'col': COL_CLOUDINARY, 'val': '완료'})
            else:
                print(f"     - 실패: {cloud_result.get('error')}")
                stats['errors'].append(f"{num}: {cloud_result.get('error')}")
                updates.append({'row': item['idx'], 'col': COL_CLOUDINARY, 'val': '실패'})

    # 시트 업데이트
    if updates and not dry_run:
        print(f"\n{'─'*60}")
        print(f"📊 구글시트 업데이트: {len(updates)}건")
        cells = [gspread.Cell(u['row'], u['col'], u['val']) for u in updates]
        sheet.update_cells(cells)
        print("  ✅ 업데이트 완료")
    elif dry_run:
        print(f"\n(dry-run 모드: 실제 업데이트 없음)")

    # 결과 요약
    print(f"\n{'='*70}")
    print("📋 결과 요약")
    print(f"{'='*70}")
    print(f"  처리 대상: {len(incomplete)}건")
    print(f"  캡션 생성: {stats['caption_created']}건")
    print(f"  메타데이터 수정: {stats['metadata_fixed']}건")
    print(f"  Cloudinary 업로드: {stats['cloudinary_uploaded']}건")
    if stats['errors']:
        print(f"  에러: {len(stats['errors'])}건")
        for e in stats['errors'][:5]:
            print(f"    - {e}")

    return stats


def main():
    args = sys.argv[1:]

    if '--scan' in args:
        reconcile_all(scan_only=True)
    elif '--dry-run' in args:
        reconcile_all(dry_run=True)
    else:
        reconcile_all(dry_run=False)


if __name__ == "__main__":
    main()
