"""
CaptionAgent - 캡션/카피 전문가 (이카피)

topics_expanded.json에서 주제 정보 로드
hashtag_strategy.json에서 해시태그 전략 로드

Author: 이카피 (Lee Copy)
"""

import json
import random
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from .base import BaseAgent, AgentResult


# 설정 파일 경로
_CONFIG_DIR = Path(__file__).parent.parent / "config"


def _load_json(filename: str) -> Dict:
    """config/ 디렉토리에서 JSON 로드"""
    path = _CONFIG_DIR / filename
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


# 주제 DB 캐싱 (topics_expanded.json)
_TOPICS_CACHE: Optional[Dict] = None


def _get_topics_db() -> Dict:
    """topics_expanded.json에서 주제 정보 로드 (캐싱)"""
    global _TOPICS_CACHE
    if _TOPICS_CACHE is not None:
        return _TOPICS_CACHE

    data = _load_json("topics_expanded.json")
    topics_map = {}
    for category_key, category in data.get("categories", {}).items():
        for topic in category.get("topics", []):
            topics_map[topic["id"]] = {
                "ko": topic["ko"],
                "safety": topic["safety"],
                "note": topic.get("note", ""),
                "category": category_key,
            }
    _TOPICS_CACHE = topics_map
    return _TOPICS_CACHE


# 해시태그 전략 캐싱
_HASHTAG_CACHE: Optional[Dict] = None


def _get_hashtag_strategy() -> Dict:
    """hashtag_strategy.json 로드 (캐싱)"""
    global _HASHTAG_CACHE
    if _HASHTAG_CACHE is not None:
        return _HASHTAG_CACHE
    _HASHTAG_CACHE = _load_json("hashtag_strategy.json")
    return _HASHTAG_CACHE


# 안전도별 이모지/급여 가능 매핑
_SAFETY_MAP = {
    "safe": {"emoji": "✅", "can_eat": "O", "label": "급여 가능!"},
    "caution": {"emoji": "⚠️", "can_eat": "△", "label": "주의해서 급여"},
    "dangerous": {"emoji": "❌", "can_eat": "X", "label": "절대 금지!"},
}


class CaptionAgent(BaseAgent):
    """캡션/카피 전문 에이전트 (이카피) - hashtag_strategy.json 연동"""

    @property
    def name(self) -> str:
        return "Caption"

    async def execute(self, input_data: Any) -> AgentResult:
        """캡션 생성 실행"""
        if isinstance(input_data, str):
            topic = input_data
            safety = None
            topic_kr = None
        else:
            topic = input_data.get("topic", "unknown")
            safety = input_data.get("safety")
            topic_kr = input_data.get("topic_kr")

        self.log(f"'{topic}' 캡션 생성 시작")

        # 주제 정보 조회 (topics_expanded.json)
        info = self._get_topic_info(topic, safety=safety, topic_kr=topic_kr)

        # 캡션 생성
        caption = self._generate_caption(topic, info)

        # 해시태그 생성 (hashtag_strategy.json)
        hashtags = self._generate_hashtags(topic, info)

        self.log(f"캡션 완료 (본문 {len(caption)}자, 해시태그 {len(hashtags)}개)")

        # AI 표기 문구 (2026-01-29 PD 지시)
        ai_disclosure = "\n\nℹ️ 일부 이미지는 AI로 생성되었습니다.\nℹ️ Some images were generated by AI."

        return AgentResult(
            success=True,
            data={
                "topic": topic,
                "caption": {
                    "full": caption + "\n\n" + " ".join(hashtags) + ai_disclosure,
                    "body": caption,
                    "hashtags": hashtags,
                    "hashtag_count": len(hashtags),
                    "character_count": len(caption)
                },
                "topic_info": info
            },
            metadata={"agent": "leecopy", "hashtag_source": "hashtag_strategy.json"}
        )

    def _get_topic_info(self, topic: str, safety: Optional[str] = None, topic_kr: Optional[str] = None) -> Dict:
        """topics_expanded.json에서 주제 정보 조회"""
        db = _get_topics_db()
        if topic in db:
            entry = db[topic]
            s = safety or entry["safety"]
            safety_info = _SAFETY_MAP.get(s, _SAFETY_MAP["safe"])
            return {
                "korean": topic_kr or entry["ko"],
                "safety": s,
                "can_eat": safety_info["can_eat"],
                "note": entry["note"],
                "category": entry["category"],
            }
        # DB에 없는 주제
        return {
            "korean": topic_kr or topic,
            "safety": safety or "unknown",
            "can_eat": "?",
            "note": "",
            "category": "unknown",
        }

    def _generate_caption(self, topic: str, info: Dict) -> str:
        """캡션 본문 생성 (Hook → Answer → Info → CTA)"""
        korean = info["korean"]
        safety = info["safety"]
        can_eat = info["can_eat"]
        note = info["note"]

        safety_info = _SAFETY_MAP.get(safety, {"emoji": "🐕", "label": "확인 필요"})

        if safety == "dangerous":
            verdict_detail = f"강아지에게 {korean}은(는) 위험해요!"
        elif safety == "caution":
            verdict_detail = f"강아지 {korean}, 조건부로 가능해요!"
        else:
            verdict_detail = f"강아지에게 {korean} 줘도 돼요!"

        note_line = f"• 참고: {note}" if note else ""

        caption = f"""강아지에게 {korean}를(을) 줘도 될까요?

{safety_info['emoji']} {safety_info['label']}
{verdict_detail}

━━━━━━━━━━━━━━━━━━━━

핵심 정보
• 급여 가능: {can_eat}
{note_line}

━━━━━━━━━━━━━━━━━━━━

스와이프해서 자세한 정보를 확인하세요!
저장해두고 필요할 때 확인하세요!

더 많은 강아지 정보 → 프로필 링크"""

        return caption.strip()

    def _generate_hashtags(self, topic: str, info: Dict) -> List[str]:
        """
        hashtag_strategy.json 기반 해시태그 생성

        2026년 Instagram 알고리즘 최적화:
        - 최대 5개 해시태그
        - 구성: reach(1) + niche(1) + topic(1) + community(1) + brand(1)
        """
        strategy = _get_hashtag_strategy()
        korean = info.get("korean", topic)

        if not strategy:
            # fallback: 기본 해시태그 5개
            return [
                "#DogsOfInstagram",
                "#GoldenRetriever",
                f"#강아지{korean}",
                "#펫스타그램",
                "#햇살이"
            ]

        # 1. 주제별 사전 정의 태그 확인
        topics_tags = strategy.get("topics", {})
        if topic in topics_tags:
            predefined = topics_tags[topic].get("tags", [])
            if predefined:
                return predefined[:5]

        # 2. 동적 생성 (5개 슬롯)
        base_tags = strategy.get("base_tags", {})
        hashtags = []

        # 슬롯 1: reach (글로벌 대형)
        reach_tags = base_tags.get("reach", [])
        if reach_tags:
            hashtags.append(random.choice(reach_tags))

        # 슬롯 2: niche (품종/타겟)
        niche_tags = base_tags.get("niche", [])
        if niche_tags:
            hashtags.append(random.choice(niche_tags))

        # 슬롯 3: topic (주제 관련 한글)
        hashtags.append(f"#강아지{korean}")

        # 슬롯 4: community (커뮤니티)
        community_tags = base_tags.get("community", [])
        if community_tags:
            hashtags.append(random.choice(community_tags))

        # 슬롯 5: brand (브랜드)
        brand_tags = base_tags.get("brand", [])
        if brand_tags:
            hashtags.append(brand_tags[0])  # 첫 번째 브랜드 태그 고정

        # 중복 제거 및 5개 보장
        result = list(dict.fromkeys(hashtags))[:5]

        # 5개 미만인 경우 fallback 추가
        fallbacks = ["#반려견", "#멍스타그램", "#강아지간식", "#펫스타그램", "#햇살이"]
        for fb in fallbacks:
            if len(result) >= 5:
                break
            if fb not in result:
                result.append(fb)

        return result[:5]

    def generate_caption_for_topic(self, topic: str) -> str:
        """간편 캡션 생성 (동기 버전)"""
        info = self._get_topic_info(topic)
        caption = self._generate_caption(topic, info)
        hashtags = self._generate_hashtags(topic, info)
        return caption + "\n\n" + " ".join(hashtags)
