#!/usr/bin/env python3
"""
📊 데이터 보강 스크립트 (업무 23-27번)

23. food_safety.json 누락 항목 추가
24. 한글명 누락 보강
25. 해시태그 데이터 생성 (스킵 - 수동 필요)
26. 캡션 템플릿 생성
27. posting_schedule.json 생성
"""

import json
from pathlib import Path
from datetime import datetime, timedelta

PROJECT_ROOT = Path(__file__).parent.parent
CONTENTS_DIR = PROJECT_ROOT / "01_contents"
CONFIG_DIR = PROJECT_ROOT / "config"
SETTINGS_DIR = CONFIG_DIR / "settings"


def check_food_safety():
    """23번: food_safety.json 누락 항목 확인"""
    print("\n📋 23. food_safety.json 누락 확인")
    print("-" * 40)

    safety_path = SETTINGS_DIR / "food_safety.json"
    safety_data = json.loads(safety_path.read_text())

    # 모든 등록된 음식 ID
    registered = set()
    for level in ["safe", "caution", "danger"]:
        registered.update(safety_data.get(level, []))

    # contents/ 폴더의 음식 ID
    missing = []
    for folder in CONTENTS_DIR.iterdir():
        if not folder.is_dir() or folder.name.startswith((".", "🔒")):
            continue

        parts = folder.name.split("_")
        if len(parts) >= 2:
            food_id = parts[1]
            if food_id not in registered and food_id not in ["reference", "sunshine"]:
                missing.append(food_id)
                print(f"  ⚠️ 누락: {food_id}")

    print(f"\n  총 {len(missing)}개 누락")
    return missing


def enrich_korean_names():
    """24번: 한글명 누락 보강"""
    print("\n📋 24. 한글명 보강")
    print("-" * 40)

    fixed = 0
    for folder in CONTENTS_DIR.iterdir():
        if not folder.is_dir() or folder.name.startswith((".", "🔒")):
            continue

        meta_path = folder / "metadata.json"
        if not meta_path.exists():
            continue

        # 폴더명에서 한글명 추출
        parts = folder.name.split("_")
        if len(parts) >= 3:
            food_kr = parts[2]
        else:
            continue

        meta = json.loads(meta_path.read_text())
        if "food_name_ko" not in meta or not meta["food_name_ko"]:
            meta["food_name_ko"] = food_kr
            meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2))
            print(f"  ✅ 추가: {folder.name} → {food_kr}")
            fixed += 1

    print(f"\n  총 {fixed}개 보강")
    return fixed


def create_caption_templates():
    """26번: 캡션 템플릿 생성"""
    print("\n📋 26. 캡션 템플릿 생성")
    print("-" * 40)

    captions_dir = CONFIG_DIR / "captions"
    captions_dir.mkdir(exist_ok=True)

    templates = {
        "SAFE": """🐕 강아지도 먹을 수 있어요!

{food_name}의 효능:
✅ {benefit_1}
✅ {benefit_2}
✅ {benefit_3}

📌 급여량: {serving_size}
⚠️ 처음 먹일 때는 소량부터!

💾 저장해두고 급여 전 확인하세요!
🐶 다른 견주님께 공유해주세요!

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI.

#강아지간식 #반려견건강 #{food_hashtag} #강아지음식 #햇살이""",

        "CAUTION": """⚠️ 주의해서 급여하세요!

{food_name} 급여 시 주의사항:
⚠️ {caution_1}
⚠️ {caution_2}
⚠️ {caution_3}

📌 권장량: {serving_size}
🚫 과급여 시 문제 발생 가능

💾 저장해두고 참고하세요!
🐶 다른 견주님께 공유해주세요!

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI.

#강아지간식 #반려견건강 #{food_hashtag} #강아지음식주의 #햇살이""",

        "DANGER": """🚫 절대 급여 금지!

{food_name}가 위험한 이유:
❌ {danger_1}
❌ {danger_2}
❌ {danger_3}

⚠️ 실수로 섭취 시 즉시 수의사 상담!

💾 저장해두고 참고하세요!
🐶 다른 견주님께 공유해주세요!

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI.

#강아지급여금지 #반려견건강 #{food_hashtag} #독성음식 #햇살이"""
    }

    for level, template in templates.items():
        path = captions_dir / f"{level}.txt"
        path.write_text(template)
        print(f"  ✅ {path.name}")

    print(f"\n  총 {len(templates)}개 템플릿 생성")


def create_posting_schedule():
    """27번: posting_schedule.json 생성"""
    print("\n📋 27. 게시 스케줄 생성")
    print("-" * 40)

    # cover_only 상태인 콘텐츠 찾기
    pending = []
    for folder in sorted(CONTENTS_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith((".", "🔒")):
            continue

        meta_path = folder / "metadata.json"
        if meta_path.exists():
            meta = json.loads(meta_path.read_text())
            status = meta.get("status", "unknown")
            if status in ("cover_only", "verified"):
                parts = folder.name.split("_")
                if len(parts) >= 2:
                    pending.append({
                        "food_id": parts[1],
                        "folder": folder.name,
                        "status": status
                    })

    # 스케줄 생성 (2일 간격)
    schedule = []
    base_date = datetime.now() + timedelta(days=1)

    for i, item in enumerate(pending[:14]):  # 2주치
        planned_date = base_date + timedelta(days=i * 2)
        schedule.append({
            "food_id": item["food_id"],
            "folder": item["folder"],
            "planned_date": planned_date.strftime("%Y-%m-%d"),
            "status": "scheduled"
        })

    result = {
        "generated_at": datetime.now().isoformat(),
        "total_pending": len(pending),
        "scheduled": len(schedule),
        "schedule": schedule
    }

    schedule_path = SETTINGS_DIR / "publish_schedule.json"
    schedule_path.write_text(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"  ✅ {schedule_path.name}")
    print(f"  대기 중: {len(pending)}개")
    print(f"  스케줄됨: {len(schedule)}개")


def run_all():
    print("=" * 60)
    print("📊 데이터 보강 시작")
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    check_food_safety()
    enrich_korean_names()
    create_caption_templates()
    create_posting_schedule()

    print("\n" + "=" * 60)
    print("✅ 데이터 보강 완료")
    print("=" * 60)


if __name__ == "__main__":
    run_all()
