#!/usr/bin/env python3
"""
DANGER 음식 캡션 수정 - 음료수 등
"""

from pathlib import Path

BASE_DIR = Path("/Users/al02399300/Desktop/Jun_AI/Dog_Contents/project_sunshine")
CONTENT_DIR = BASE_DIR / "content/images"

# DANGER 음료수 목록
DANGER_BEVERAGES = {
    'budweiser': ('버드와이저', '맥주(알코올)'),
    'cass_beer': ('카스맥주', '맥주(알코올)'),
    'coca_cola': ('코카콜라', '탄산음료(카페인+설탕)'),
    'fanta': ('환타', '탄산음료(설탕)'),
    'milkis': ('밀키스', '탄산음료(설탕)'),
    'perrier': ('페리에', '탄산수'),
    'soju': ('소주', '알코올'),
    'starbucks_coffee': ('스타벅스커피', '커피(카페인)'),
    'sprite': ('스프라이트', '탄산음료(설탕)'),
}

def generate_danger_caption_instagram(topic_kr, topic_en, danger_reason):
    return f"""🚫 {topic_kr}, 강아지에게 주지 마세요!

우리 댕댕이한테 {topic_kr}은(는) 위험해요 ⚠️

❌ {danger_reason} - 강아지에게 해로워요
❌ 실수로 마셨다면 즉시 병원으로!

📌 저장해두고 가족들과 공유하세요!

💬 우리 집 댕댕이 이름은?
댓글로 알려주세요! 🐾

#강아지 #반려견 #강아지음식 #댕댕이 #골든리트리버 #햇살이 #{topic_en} #{topic_kr} #강아지금지음식 #펫스타그램 #멍스타그램

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI."""

def generate_danger_caption_threads(topic_kr, topic_en, danger_reason):
    return f"""🚫 {topic_kr} - 강아지 금지!

❌ {danger_reason}
절대 주지 마세요 ⚠️

#강아지 #{topic_kr} #반려견

ℹ️ AI 생성 이미지 포함"""

def main():
    print("=" * 60)
    print("🔧 DANGER 음료수 캡션 수정")
    print("=" * 60)

    fixed = 0

    for folder in sorted(CONTENT_DIR.iterdir()):
        if not folder.is_dir():
            continue

        folder_name = folder.name

        for eng_name, (kr_name, reason) in DANGER_BEVERAGES.items():
            if eng_name in folder_name:
                # Instagram 캡션 수정
                caption_insta = folder / "caption_instagram.txt"
                caption_threads = folder / "caption_threads.txt"

                if caption_insta.exists():
                    caption_insta.write_text(
                        generate_danger_caption_instagram(kr_name, eng_name, reason),
                        encoding='utf-8'
                    )

                if caption_threads.exists():
                    caption_threads.write_text(
                        generate_danger_caption_threads(kr_name, eng_name, reason),
                        encoding='utf-8'
                    )

                print(f"  ✅ {folder_name} → DANGER 캡션 적용")
                fixed += 1
                break

    print(f"\n✅ 총 {fixed}개 수정 완료")

if __name__ == "__main__":
    main()
