#!/usr/bin/env python3
"""
WO-2026-0205-004: B그룹 바디+CTA+캡션 렌더링

사용법:
    python wo_004_batch.py forbidden
    python wo_004_batch.py danger
    python wo_004_batch.py caution
    python wo_004_batch.py safe
    python wo_004_batch.py all

산출물 (1건당):
    - text.json (config/settings/{food_id}_text.json)
    - 바디①: {food_id}_01.png
    - 바디②: {food_id}_02.png
    - CTA: {food_id}_03.png
    - caption_instagram.txt
    - caption_threads.txt
    - metadata.json
"""

import os
import sys
import json
import hashlib
import shutil
from pathlib import Path
from datetime import datetime

try:
    from PIL import Image
except ImportError:
    print("[ERROR] Pillow 필요: pip install Pillow")
    sys.exit(1)

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

from pipeline.pillow_overlay import (
    render_cover, render_body, render_cta,
    build_validation_config, get_safety_color,
)
from pipeline.validators_strict import (
    validate_before_render, validate_v31_slide, strip_emoji,
)

# ============================================================
# 경로
# ============================================================
BODY_READY_DIR = PROJECT_ROOT / "contents" / "2_body_ready"
COVER_ONLY_DIR = PROJECT_ROOT / "contents" / "1_cover_only"
COVER_SOURCE_DIR = (
    PROJECT_ROOT / "backup_2026-02-03" / "content" / "images"
    / "000_cover" / "02_ready"
)
BEST_CTA_DIR = PROJECT_ROOT / "contents" / "sunshine" / "cta_source" / "best_cta"
TEXT_JSON_DIR = PROJECT_ROOT / "config" / "settings"
TARGET_SIZE = (1080, 1080)

# ============================================================
# CTA 선택 (SHA256 해시)
# ============================================================
def select_cta_image(food_id: str) -> Path:
    cta_files = sorted([f for f in BEST_CTA_DIR.iterdir()
                        if f.suffix.lower() in ('.jpg', '.jpeg', '.png')])
    if not cta_files:
        raise FileNotFoundError(f"CTA 이미지 없음: {BEST_CTA_DIR}")
    h = hashlib.sha256(food_id.encode()).hexdigest()
    idx = int(h, 16) % len(cta_files)
    return cta_files[idx]


# ============================================================
# 캡션 생성
# ============================================================
def generate_instagram_caption(food_id, food_ko, safety, body1, body2):
    """인스타그램 캡션 생성 (3~5줄, 해시태그 최대 5개)"""
    safety_upper = safety.upper()

    if safety_upper == "FORBIDDEN":
        lines = [
            f"⛔ {food_ko}, 강아지에게 절대 금지!",
            "",
            f"{body1['subtitle']}",
            f"증상 발견 시 즉시 동물병원으로!",
            "",
            f"📌 저장해두고 주변 견주에게 공유하세요.",
            "",
            f"#강아지금지음식 #반려견건강 #강아지음식 #{food_ko.replace(' ','')} @sunshinedogfood",
            "",
            "ℹ️ 일부 이미지는 AI로 생성되었습니다.",
            "ℹ️ Some images were generated by AI.",
        ]
    elif safety_upper == "DANGER":
        lines = [
            f"⚠️ {food_ko}, 강아지에게 위험해요!",
            "",
            f"{body1['subtitle']}",
            f"{body2['subtitle']}",
            "",
            f"📌 저장해두고 참고하세요!",
            "",
            f"#강아지위험음식 #반려견건강 #강아지음식 #{food_ko.replace(' ','')} @sunshinedogfood",
            "",
            "ℹ️ 일부 이미지는 AI로 생성되었습니다.",
            "ℹ️ Some images were generated by AI.",
        ]
    elif safety_upper == "CAUTION":
        lines = [
            f"🟡 {food_ko}, 강아지 급여 시 주의하세요!",
            "",
            f"{body1['subtitle']}",
            f"{body2['subtitle']}",
            "",
            f"📌 저장 & 공유로 다른 견주에게도 알려주세요!",
            "",
            f"#강아지음식 #반려견건강 #강아지간식 #{food_ko.replace(' ','')} @sunshinedogfood",
            "",
            "ℹ️ 일부 이미지는 AI로 생성되었습니다.",
            "ℹ️ Some images were generated by AI.",
        ]
    else:  # SAFE
        lines = [
            f"🐕 {food_ko}, 강아지 급여 가능!",
            "",
            f"{body1['subtitle']}",
            f"{body2['subtitle']}",
            "",
            f"📌 저장해두고 급여할 때 참고하세요!",
            "",
            f"#강아지음식 #반려견건강 #강아지간식 #{food_ko.replace(' ','')} @sunshinedogfood",
            "",
            "ℹ️ 일부 이미지는 AI로 생성되었습니다.",
            "ℹ️ Some images were generated by AI.",
        ]

    return "\n".join(lines)


def generate_threads_caption(food_id, food_ko, safety, body1, body2):
    """쓰레드 캡션 생성 (2~3줄, 해시태그 없음)"""
    safety_upper = safety.upper()

    if safety_upper == "FORBIDDEN":
        lines = [
            f"⛔ {food_ko}는 강아지에게 절대 금지예요. {body1['subtitle']}",
            f"소량도 위험하니 보관에 주의하세요!",
            "",
            "ℹ️ AI 생성 이미지 포함",
        ]
    elif safety_upper == "DANGER":
        lines = [
            f"⚠️ {food_ko}, 강아지한테 위험해요. {body1['subtitle']}",
            f"{body2['subtitle']}",
            "",
            "ℹ️ AI 생성 이미지 포함",
        ]
    elif safety_upper == "CAUTION":
        lines = [
            f"🟡 {food_ko}, 급여 가능하지만 주의! {body1['subtitle']}",
            f"{body2['subtitle']}",
            "",
            "ℹ️ AI 생성 이미지 포함",
        ]
    else:  # SAFE
        lines = [
            f"🐕 {food_ko}, 강아지 급여 OK! {body1['subtitle']}",
            f"{body2['subtitle']}",
            "",
            "ℹ️ AI 생성 이미지 포함",
        ]

    return "\n".join(lines)


# ============================================================
# 메타데이터 생성
# ============================================================
def generate_metadata(food_id, food_ko, safety, folder_name, slides_rendered,
                      cover_file, cta_file, wo_number="WO-2026-0205-004"):
    return {
        "food_id": food_id,
        "food_name_ko": food_ko,
        "safety": safety.upper(),
        "safety_color": {
            "safe": "#4CAF50", "caution": "#FFD93D",
            "danger": "#FF6B6B", "forbidden": "#FF5252",
        }.get(safety.lower(), "#4CAF50"),
        "folder": folder_name,
        "slides": {
            "cover": f"{food_id}_00.png",
            "body1": f"{food_id}_01.png",
            "body2": f"{food_id}_02.png",
            "cta": f"{food_id}_03.png",
        },
        "cover_source": cover_file,
        "cta_source": cta_file,
        "slides_rendered": slides_rendered,
        "pipeline_version": "v3.1",
        "work_order": wo_number,
        "rendered_at": datetime.now().isoformat(),
        "status": "body_ready",
    }


# ============================================================
# text.json 생성/저장
# ============================================================
def save_text_json(food_id, cover_title, body1, body2, cta):
    data = [
        {"slide": 0, "type": "cover", "title": cover_title, "subtitle": ""},
        {"slide": 1, "type": "content_bottom",
         "title": body1["title"], "subtitle": body1["subtitle"]},
        {"slide": 2, "type": "content_bottom",
         "title": body2["title"], "subtitle": body2["subtitle"]},
        {"slide": 3, "type": "cta",
         "title": cta["title"], "subtitle": cta["subtitle"]},
    ]
    path = TEXT_JSON_DIR / f"{food_id}_text.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return path


# ============================================================
# 폴더 매핑 헬퍼
# ============================================================
def find_folder(food_id):
    """food_id로 기존 폴더 찾기 (body_ready 먼저, 그다음 cover_only)"""
    for base_dir in [BODY_READY_DIR, COVER_ONLY_DIR]:
        for d in base_dir.iterdir():
            if not d.is_dir():
                continue
            parts = d.name.split("_", 2)
            if len(parts) >= 2 and parts[1] == food_id:
                return d
    return None


def find_cover_source(food_id, cover_file_hint=""):
    """커버 소스 파일 찾기"""
    if cover_file_hint:
        p = COVER_SOURCE_DIR / cover_file_hint
        if p.exists():
            return p
    # food_id로 검색
    for f in COVER_SOURCE_DIR.glob("cover_*"):
        fname = f.stem.lower()
        if food_id.lower() in fname:
            return f
    return None


# ============================================================
# 단일 아이템 처리
# ============================================================
def process_item(item, dry_run=False):
    """단일 아이템 처리: 렌더링 + 캡션 + 메타데이터"""
    food_id = item["food_id"]
    food_ko = item["food_ko"]
    safety = item["safety"]
    cover_file = item.get("cover_file", "")
    folder_name = item.get("folder", "")
    body1 = item["body1"]
    body2 = item["body2"]
    cta = item["cta"]
    cover_title = item.get("cover_title", food_id.upper())

    result = {
        "food_id": food_id,
        "food_ko": food_ko,
        "safety": safety.upper(),
        "text_json": False,
        "render_01": False,
        "render_02": False,
        "render_03": False,
        "caption_insta": False,
        "caption_threads": False,
        "metadata": False,
        "validators": "N/A",
        "errors": [],
        "skipped": False,
    }

    # 폴더 찾기
    folder = find_folder(food_id)
    if not folder:
        # 커버 소스로 폴더 생성 시도
        cover_src = find_cover_source(food_id, cover_file)
        if not cover_src:
            result["errors"].append(f"폴더 없음 + 커버소스 없음")
            result["skipped"] = True
            return result

        # 번호 추출
        num = cover_src.stem.split("_")[1] if "_" in cover_src.stem else "999"
        folder_name_new = f"{int(num):03d}_{food_id}_{food_ko}"
        folder = COVER_ONLY_DIR / folder_name_new
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "archive").mkdir(exist_ok=True)
        print(f"    새 폴더 생성: {folder_name_new}")

    folder_name = folder.name

    # body_ready로 이동 필요 여부
    if COVER_ONLY_DIR in folder.parents or folder.parent == COVER_ONLY_DIR:
        dest = BODY_READY_DIR / folder.name
        if not dest.exists():
            shutil.move(str(folder), str(dest))
            folder = dest
            print(f"    → 2_body_ready/ 이동")
        else:
            folder = dest

    archive = folder / "archive"
    archive.mkdir(exist_ok=True)

    # 커버 소스 확인
    cover_src = find_cover_source(food_id, cover_file)
    if not cover_src:
        result["errors"].append(f"커버소스 없음: {cover_file}")
        result["skipped"] = True
        return result

    # [1] text.json 생성
    try:
        save_text_json(food_id, cover_title, body1, body2, cta)
        result["text_json"] = True
    except Exception as e:
        result["errors"].append(f"text.json 실패: {e}")

    validators_passed = 0
    validators_total = 0

    # [2-4] 렌더링 (이미 있으면 스킵)
    for slide_num, slide_type, text_data in [
        ("01", "body", body1),
        ("02", "body", body2),
    ]:
        out_file = folder / f"{food_id}_{slide_num}.png"
        if out_file.exists() and os.path.getsize(out_file) > 10000:
            result[f"render_{slide_num}"] = True
            print(f"    _{slide_num} 이미 존재 → 스킵")
            validators_passed += 3
            validators_total += 3
            continue

        try:
            bg_file = archive / f"{food_id}_{slide_num}_bg.png"
            if not bg_file.exists():
                shutil.copy2(cover_src, bg_file)

            v_config = build_validation_config(slide_type, safety)
            rel_path = str(bg_file.relative_to(PROJECT_ROOT))
            validate_before_render(slide_type, rel_path, v_config)
            validators_passed += 1
            validators_total += 1

            img = Image.open(bg_file).resize(TARGET_SIZE, Image.LANCZOS)
            title_clean = strip_emoji(text_data["title"])
            sub_clean = strip_emoji(text_data["subtitle"])
            img = render_body(img, title_clean, sub_clean, safety)
            img.save(out_file, "PNG")

            validate_v31_slide(slide_type, v_config, str(out_file.relative_to(PROJECT_ROOT)))
            validators_passed += 2
            validators_total += 2

            result[f"render_{slide_num}"] = True
            print(f"    _{slide_num} 렌더링 완료 ({os.path.getsize(out_file)//1024}KB)")
        except Exception as e:
            validators_total += 2
            result["errors"].append(f"_{slide_num} 실패: {e}")
            print(f"    _{slide_num} 실패: {e}")

    # CTA 렌더링
    out_03 = folder / f"{food_id}_03.png"
    cta_src_file = ""
    if out_03.exists() and os.path.getsize(out_03) > 10000:
        result["render_03"] = True
        print(f"    _03 이미 존재 → 스킵")
        validators_passed += 3
        validators_total += 3
    else:
        try:
            cta_src = select_cta_image(food_id)
            cta_src_file = cta_src.name
            bg_03 = archive / f"{food_id}_03_bg.png"
            shutil.copy2(cta_src, bg_03)

            v_config = build_validation_config("cta", safety)
            rel_path = str(bg_03.relative_to(PROJECT_ROOT))
            validate_before_render("cta", rel_path, v_config)
            validators_passed += 1
            validators_total += 1

            img = Image.open(bg_03).resize(TARGET_SIZE, Image.LANCZOS)
            title_clean = strip_emoji(cta["title"])
            sub_clean = strip_emoji(cta["subtitle"])
            img = render_cta(img, title_clean, sub_clean, bg_path=rel_path)
            img.save(out_03, "PNG")

            validate_v31_slide("cta", v_config, str(out_03.relative_to(PROJECT_ROOT)))
            validators_passed += 2
            validators_total += 2

            result["render_03"] = True
            print(f"    _03 CTA 완료 ({os.path.getsize(out_03)//1024}KB)")
        except Exception as e:
            validators_total += 2
            result["errors"].append(f"_03 CTA 실패: {e}")
            print(f"    _03 CTA 실패: {e}")

    result["validators"] = f"{validators_passed}/{validators_total}"

    # [5] 캡션 생성 (항상 재생성)
    try:
        insta_caption = generate_instagram_caption(food_id, food_ko, safety, body1, body2)
        with open(folder / "caption_instagram.txt", "w", encoding="utf-8") as f:
            f.write(insta_caption)
        result["caption_insta"] = True
    except Exception as e:
        result["errors"].append(f"인스타 캡션 실패: {e}")

    try:
        threads_caption = generate_threads_caption(food_id, food_ko, safety, body1, body2)
        with open(folder / "caption_threads.txt", "w", encoding="utf-8") as f:
            f.write(threads_caption)
        result["caption_threads"] = True
    except Exception as e:
        result["errors"].append(f"쓰레드 캡션 실패: {e}")

    # [6] 메타데이터 생성
    try:
        slides_rendered = sum([
            result["render_01"], result["render_02"], result["render_03"]
        ])
        meta = generate_metadata(
            food_id, food_ko, safety, folder_name,
            slides_rendered, cover_src.name if cover_src else "",
            cta_src_file,
        )
        with open(folder / "metadata.json", "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
        result["metadata"] = True
    except Exception as e:
        result["errors"].append(f"메타데이터 실패: {e}")

    return result


# ============================================================
# 아이템 정의 (75건)
# ============================================================
ITEMS = {
    "forbidden": [
        {
            "food_id": "brownie", "food_ko": "브라우니", "safety": "forbidden",
            "folder": "095_brownie_브라우니",
            "cover_file": "cover_95_브라우니_brownie.png",
            "cover_title": "BROWNIE",
            "body1": {"title": "절대 금지!", "subtitle": "초콜릿 함유, 테오브로민 독성"},
            "body2": {"title": "증상 & 대처", "subtitle": "구토, 경련 시 즉시 동물병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "reeses", "food_ko": "리세스", "safety": "forbidden",
            "folder": "124_reeses_리세스",
            "cover_file": "cover_124_리세스_reeses.png",
            "cover_title": "REESE'S",
            "body1": {"title": "절대 금지!", "subtitle": "초콜릿+땅콩, 이중 위험"},
            "body2": {"title": "증상 & 대처", "subtitle": "구토, 설사 시 즉시 동물병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "soju", "food_ko": "소주", "safety": "forbidden",
            "folder": "128_soju_소주",
            "cover_file": "cover_128_소주_soju.png",
            "cover_title": "SOJU",
            "body1": {"title": "절대 금지!", "subtitle": "알코올 독성, 소량도 치명적"},
            "body2": {"title": "증상 & 대처", "subtitle": "비틀거림, 호흡곤란 시 응급실"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "green_onion", "food_ko": "대파", "safety": "forbidden",
            "cover_file": "",
            "cover_title": "GREEN ONION",
            "body1": {"title": "절대 금지!", "subtitle": "알리움 성분, 적혈구 파괴"},
            "body2": {"title": "증상 & 대처", "subtitle": "빈혈, 혈뇨 시 즉시 동물병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "pizza", "food_ko": "피자", "safety": "forbidden",
            "folder": "121_pizza_피자",
            "cover_file": "cover_121_피자_pizza.png",
            "cover_title": "PIZZA",
            "body1": {"title": "절대 금지!", "subtitle": "양파/마늘/치즈/기름 복합 위험"},
            "body2": {"title": "증상 & 대처", "subtitle": "구토, 췌장염 위험 즉시 병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "ramen", "food_ko": "라면", "safety": "forbidden",
            "folder": "086_ramen_라면",
            "cover_file": "cover_75_라면_ramen.png",
            "cover_title": "RAMEN",
            "body1": {"title": "절대 금지!", "subtitle": "나트륨 과다, 양파/마늘 독성"},
            "body2": {"title": "증상 & 대처", "subtitle": "구토, 탈수 시 즉시 동물병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
    ],
    "danger": [
        {
            "food_id": "bibimbap", "food_ko": "비빔밥", "safety": "danger",
            "folder": "081_bibimbap_비빔밥",
            "cover_file": "cover_81_비빔밥_bibimbap.png",
            "cover_title": "BIBIMBAP",
            "body1": {"title": "위험해요!", "subtitle": "양념, 참기름, 고추장 자극"},
            "body2": {"title": "대처법", "subtitle": "무양념 밥+나물만 소량 가능"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "jjajangmyeon", "food_ko": "짜장면", "safety": "danger",
            "folder": "082_jjajangmyeon_짜장면",
            "cover_file": "cover_82_짜장면_jjajangmyeon.png",
            "cover_title": "JJAJANGMYEON",
            "body1": {"title": "위험해요!", "subtitle": "춘장+양파, 나트륨 과다"},
            "body2": {"title": "대처법", "subtitle": "면 소량도 소화 부담, 급여 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "bulgogi", "food_ko": "불고기", "safety": "danger",
            "folder": "090_bulgogi_불고기",
            "cover_file": "cover_90_불고기_bulgogi.png",
            "cover_title": "BULGOGI",
            "body1": {"title": "위험해요!", "subtitle": "양념(간장, 마늘, 설탕) 독성"},
            "body2": {"title": "대처법", "subtitle": "무양념 고기만 익혀서 소량 가능"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "cake", "food_ko": "케이크", "safety": "danger",
            "folder": "091_cake_케이크",
            "cover_file": "cover_91_케이크_cake.png",
            "cover_title": "CAKE",
            "body1": {"title": "위험해요!", "subtitle": "설탕, 크림, 초콜릿 위험"},
            "body2": {"title": "대처법", "subtitle": "비만, 췌장염 유발 급여 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "dakgangjeong", "food_ko": "닭강정", "safety": "danger",
            "folder": "102_dakgangjeong_닭강정",
            "cover_file": "cover_102_닭강정_dakgangjeong.png",
            "cover_title": "DAKGANGJEONG",
            "body1": {"title": "위험해요!", "subtitle": "양념+튀김, 나트륨/지방 과다"},
            "body2": {"title": "대처법", "subtitle": "무양념 닭가슴살로 대체 급여"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "milk", "food_ko": "바나나우유", "safety": "danger",
            "folder": "152_banana_milk_바나나우유",
            "cover_file": "cover_106_바나나우유_banana_milk.png",
            "cover_title": "BANANA MILK",
            "body1": {"title": "위험해요!", "subtitle": "유당불내증 + 설탕 과다"},
            "body2": {"title": "대처법", "subtitle": "설사, 복부팽만 시 급여 중단"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "doritos", "food_ko": "도리토스", "safety": "danger",
            "folder": "113_doritos_도리토스",
            "cover_file": "cover_113_도리토스_doritos.png",
            "cover_title": "DORITOS",
            "body1": {"title": "위험해요!", "subtitle": "양파/마늘 분말, 나트륨 과다"},
            "body2": {"title": "대처법", "subtitle": "1장도 위험, 급여 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "fanta", "food_ko": "환타", "safety": "danger",
            "folder": "114_fanta_환타",
            "cover_file": "cover_114_환타_fanta.png",
            "cover_title": "FANTA",
            "body1": {"title": "위험해요!", "subtitle": "설탕+카페인+인공감미료 독성"},
            "body2": {"title": "대처법", "subtitle": "탈수 위험, 깨끗한 물만 급여"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "lays", "food_ko": "레이즈", "safety": "danger",
            "folder": "118_lays_레이즈",
            "cover_file": "cover_118_레이즈_lays.png",
            "cover_title": "LAY'S",
            "body1": {"title": "위험해요!", "subtitle": "나트륨+양파 분말, 지방 과다"},
            "body2": {"title": "대처법", "subtitle": "소화불량, 구토 시 급여 중단"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "milkis", "food_ko": "밀키스", "safety": "danger",
            "folder": "119_milkis_밀키스",
            "cover_file": "cover_119_밀키스_milkis.png",
            "cover_title": "MILKIS",
            "body1": {"title": "위험해요!", "subtitle": "탄산+설탕+유당, 복부팽만"},
            "body2": {"title": "대처법", "subtitle": "가스, 설사 시 급여 중단"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "skittles", "food_ko": "스키틀즈", "safety": "danger",
            "folder": "127_skittles_스키틀즈",
            "cover_file": "cover_127_스키틀즈_skittles.png",
            "cover_title": "SKITTLES",
            "body1": {"title": "위험해요!", "subtitle": "설탕+인공색소+자일리톨 위험"},
            "body2": {"title": "대처법", "subtitle": "저혈당, 경련 시 즉시 병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "starburst", "food_ko": "스타버스트", "safety": "danger",
            "folder": "130_starburst_스타버스트",
            "cover_file": "cover_130_스타버스트_starburst.png",
            "cover_title": "STARBURST",
            "body1": {"title": "위험해요!", "subtitle": "설탕+인공향료, 질식 위험"},
            "body2": {"title": "대처법", "subtitle": "끈적한 식감, 기도폐색 주의"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "sprite", "food_ko": "스프라이트", "safety": "danger",
            "folder": "133_sprite_스프라이트",
            "cover_file": "cover_133_스프라이트_sprite.png",
            "cover_title": "SPRITE",
            "body1": {"title": "위험해요!", "subtitle": "탄산+설탕+인공감미료 독성"},
            "body2": {"title": "대처법", "subtitle": "복부팽만, 구토 시 급여 중단"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "raisin", "food_ko": "건포도", "safety": "danger",
            "folder": "062_raisin_건포도",
            "cover_file": "cover_156_건포도_raisin.png",
            "cover_title": "RAISIN",
            "body1": {"title": "위험해요!", "subtitle": "포도 성분, 급성 신부전 유발"},
            "body2": {"title": "증상 & 대처", "subtitle": "구토, 무기력 시 즉시 병원"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "lemon", "food_ko": "레몬", "safety": "danger",
            "cover_file": "cover_158_레몬_lemon.png",
            "cover_title": "LEMON",
            "body1": {"title": "위험해요!", "subtitle": "구연산 과다, 위장 자극"},
            "body2": {"title": "대처법", "subtitle": "구토, 설사 시 급여 중단"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "bacon", "food_ko": "베이컨", "safety": "danger",
            "folder": "105_bacon_베이컨",
            "cover_file": "cover_105_베이컨_bacon.png",
            "cover_title": "BACON",
            "body1": {"title": "위험해요!", "subtitle": "나트륨+지방 과다, 췌장염 위험"},
            "body2": {"title": "대처법", "subtitle": "구토, 설사 시 즉시 급여 중단"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "donut", "food_ko": "도넛", "safety": "danger",
            "folder": "092_donut_도넛",
            "cover_file": "cover_92_도넛_donut.png",
            "cover_title": "DONUT",
            "body1": {"title": "위험해요!", "subtitle": "설탕+지방 과다, 비만 유발"},
            "body2": {"title": "대처법", "subtitle": "초콜릿 도넛은 절대 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
    ],
    "caution": [
        {
            "food_id": "nuts", "food_ko": "견과류", "safety": "caution",
            "folder": "031_nuts_견과류",
            "cover_file": "cover_31_견과류_nuts.png",
            "cover_title": "NUTS",
            "body1": {"title": "주의 급여!", "subtitle": "소량 OK, 마카다미아 절대 금지"},
            "body2": {"title": "급여 방법", "subtitle": "무염, 잘게 부숴서 소량만"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "almonds", "food_ko": "아몬드", "safety": "caution",
            "folder": "032_almonds_아몬드",
            "cover_file": "cover_32_아몬드_almonds.png",
            "cover_title": "ALMONDS",
            "body1": {"title": "주의 급여!", "subtitle": "무염만 OK, 통째로 질식 위험"},
            "body2": {"title": "급여 방법", "subtitle": "잘게 부숴서 1~2알, 무염 필수"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "baguette", "food_ko": "바게트", "safety": "caution",
            "folder": "034_baguette_바게트",
            "cover_file": "cover_34_바게트_baguette.png",
            "cover_title": "BAGUETTE",
            "body1": {"title": "주의 급여!", "subtitle": "밀 알레르기 확인, 소량만"},
            "body2": {"title": "급여 방법", "subtitle": "무첨가 빵 한 조각, 버터 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "tteokguk", "food_ko": "떡국", "safety": "caution",
            "folder": "077_tteokguk_떡국",
            "cover_file": "cover_76_떡국_tteokguk.png",
            "cover_title": "TTEOKGUK",
            "body1": {"title": "주의 급여!", "subtitle": "떡 질식 위험, 양념 국물 금지"},
            "body2": {"title": "급여 방법", "subtitle": "떡만 잘게 잘라 1~2조각"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "kimbap", "food_ko": "김밥", "safety": "caution",
            "folder": "080_kimbap_김밥",
            "cover_file": "cover_80_김밥_kimbap.png",
            "cover_title": "KIMBAP",
            "body1": {"title": "주의 급여!", "subtitle": "참기름+당근OK, 단무지/시금치 제거"},
            "body2": {"title": "급여 방법", "subtitle": "속재료 확인 후 1~2줄만"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "udon", "food_ko": "우동", "safety": "caution",
            "folder": "083_udon_우동",
            "cover_file": "cover_83_우동_udon.png",
            "cover_title": "UDON",
            "body1": {"title": "주의 급여!", "subtitle": "면만 가능, 국물 나트륨 과다"},
            "body2": {"title": "급여 방법", "subtitle": "삶은 면 소량, 양념 국물 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "toast", "food_ko": "토스트", "safety": "caution",
            "folder": "087_toast_토스트",
            "cover_file": "cover_87_토스트_toast.png",
            "cover_title": "TOAST",
            "body1": {"title": "주의 급여!", "subtitle": "무첨가만 OK, 잼/버터 금지"},
            "body2": {"title": "급여 방법", "subtitle": "식빵 한 조각, 무첨가 필수"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "muffin", "food_ko": "머핀", "safety": "caution",
            "folder": "096_muffin_머핀",
            "cover_file": "cover_96_머핀_muffin.png",
            "cover_title": "MUFFIN",
            "body1": {"title": "주의 급여!", "subtitle": "설탕 과다, 초콜릿칩 확인 필수"},
            "body2": {"title": "급여 방법", "subtitle": "플레인만 한 입, 토핑 제거"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "pancake", "food_ko": "팬케이크", "safety": "caution",
            "folder": "097_pancake_팬케이크",
            "cover_file": "cover_97_팬케이크_pancake.png",
            "cover_title": "PANCAKE",
            "body1": {"title": "주의 급여!", "subtitle": "무첨가만 OK, 시럽/버터 금지"},
            "body2": {"title": "급여 방법", "subtitle": "플레인 한 조각, 소량만"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "waffle", "food_ko": "와플", "safety": "caution",
            "folder": "098_waffle_와플",
            "cover_file": "cover_98_와플_waffle.png",
            "cover_title": "WAFFLE",
            "body1": {"title": "주의 급여!", "subtitle": "설탕/버터 과다, 플레인만"},
            "body2": {"title": "급여 방법", "subtitle": "토핑 없이 한 조각만 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "cereal", "food_ko": "시리얼", "safety": "caution",
            "folder": "099_cereal_시리얼",
            "cover_file": "cover_99_시리얼_cereal.png",
            "cover_title": "CEREAL",
            "body1": {"title": "주의 급여!", "subtitle": "설탕/초콜릿 코팅 금지"},
            "body2": {"title": "급여 방법", "subtitle": "무가당 플레인 소량, 우유 없이"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "granola", "food_ko": "그래놀라", "safety": "caution",
            "folder": "100_granola_그래놀라",
            "cover_file": "cover_100_그래놀라_granola.png",
            "cover_title": "GRANOLA",
            "body1": {"title": "주의 급여!", "subtitle": "건포도/초콜릿 혼입 확인 필수"},
            "body2": {"title": "급여 방법", "subtitle": "무첨가 오트만 소량, 견과 제거"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "meatball", "food_ko": "미트볼", "safety": "caution",
            "folder": "103_meatball_미트볼",
            "cover_file": "cover_103_미트볼_meatball.png",
            "cover_title": "MEATBALL",
            "body1": {"title": "주의 급여!", "subtitle": "양파/마늘 양념 확인 필수"},
            "body2": {"title": "급여 방법", "subtitle": "무양념 고기만 익혀서 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "croissant", "food_ko": "크루아상", "safety": "caution",
            "folder": "111_croissant_크루아상",
            "cover_file": "cover_111_크루아상_croissant.png",
            "cover_title": "CROISSANT",
            "body1": {"title": "주의 급여!", "subtitle": "버터 과다, 소화 부담"},
            "body2": {"title": "급여 방법", "subtitle": "한 조각 이하, 초콜릿 크루아상 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "perrier", "food_ko": "페리에", "safety": "caution",
            "folder": "120_perrier_페리에",
            "cover_file": "cover_120_페리에_perrier.png",
            "cover_title": "PERRIER",
            "body1": {"title": "주의 급여!", "subtitle": "탄산 가스, 복부팽만 유발"},
            "body2": {"title": "급여 방법", "subtitle": "탄산 빼고 소량, 깨끗한 물 우선"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "ritz", "food_ko": "리츠", "safety": "caution",
            "folder": "125_ritz_리츠",
            "cover_file": "cover_125_리츠_ritz.png",
            "cover_title": "RITZ",
            "body1": {"title": "주의 급여!", "subtitle": "나트륨+지방, 양파 분말 확인"},
            "body2": {"title": "급여 방법", "subtitle": "1~2장 이하, 자주 급여 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "mushroom", "food_ko": "버섯", "safety": "caution",
            "folder": "175_mushroom_버섯",
            "cover_file": "cover_165_버섯_mushroom.png",
            "cover_title": "MUSHROOM",
            "body1": {"title": "주의 급여!", "subtitle": "마트 버섯만 OK, 야생 버섯 금지"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 소량, 양념 없이"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "persimmon_ripe", "food_ko": "홍시", "safety": "caution",
            "cover_file": "",
            "cover_title": "PERSIMMON",
            "body1": {"title": "주의 급여!", "subtitle": "씨 제거 필수, 장폐색 위험"},
            "body2": {"title": "급여 방법", "subtitle": "과육만 소량, 소형견 1조각"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "plum", "food_ko": "자두", "safety": "caution",
            "cover_file": "cover_151_자두_plum.png",
            "cover_title": "PLUM",
            "body1": {"title": "주의 급여!", "subtitle": "씨 시안화물, 반드시 제거"},
            "body2": {"title": "급여 방법", "subtitle": "과육만 소량, 소형견 1~2조각"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "dumpling", "food_ko": "만두", "safety": "caution",
            "cover_file": "",
            "cover_title": "DUMPLING",
            "body1": {"title": "주의 급여!", "subtitle": "속재료 양파/마늘/부추 확인"},
            "body2": {"title": "급여 방법", "subtitle": "만두피만 소량, 속 재료 제거"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
    ],
    "safe": [
        {
            "food_id": "bean_sprouts", "food_ko": "숙주나물", "safety": "safe",
            "cover_file": "",
            "cover_title": "BEAN SPROUTS",
            "body1": {"title": "먹어도 돼요!", "subtitle": "비타민C 풍부, 저칼로리"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 무양념, 소량 급여"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "melon", "food_ko": "멜론", "safety": "safe",
            "folder": "046_melon_멜론",
            "cover_file": "cover_45_멜론_melon.png",
            "cover_title": "MELON",
            "body1": {"title": "먹어도 돼요!", "subtitle": "수분 보충, 비타민A 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "씨/껍질 제거, 소형견 2~3조각"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "pomegranate", "food_ko": "석류", "safety": "safe",
            "folder": "050_pomegranate_석류",
            "cover_file": "cover_49_석류_pomegranate.png",
            "cover_title": "POMEGRANATE",
            "body1": {"title": "먹어도 돼요!", "subtitle": "항산화 풍부, 면역력 강화"},
            "body2": {"title": "급여 방법", "subtitle": "씨 제거, 과육만 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "kimchi", "food_ko": "김치", "safety": "safe",
            "folder": "066_kimchi_김치",
            "cover_file": "cover_65_김치_kimchi.png",
            "cover_title": "KIMCHI",
            "body1": {"title": "소량 가능!", "subtitle": "발효식품, 나트륨 주의"},
            "body2": {"title": "급여 방법", "subtitle": "물에 헹궈 소량만, 매운 양념 주의"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "quail_egg", "food_ko": "메추리알", "safety": "safe",
            "cover_file": "",
            "cover_title": "QUAIL EGG",
            "body1": {"title": "먹어도 돼요!", "subtitle": "고단백, 비타민B 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 하루 1~2개"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "fried_chicken", "food_ko": "후라이드치킨", "safety": "safe",
            "cover_file": "",
            "cover_title": "FRIED CHICKEN",
            "body1": {"title": "껍질 제거 시 OK!", "subtitle": "기름/양념/뼈 제거 필수"},
            "body2": {"title": "급여 방법", "subtitle": "살코기만 소량, 튀김옷 제거"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "chicken_skewer", "food_ko": "닭꼬치", "safety": "safe",
            "cover_file": "",
            "cover_title": "CHICKEN SKEWER",
            "body1": {"title": "살코기만 OK!", "subtitle": "양념/꼬치 제거 후 급여"},
            "body2": {"title": "급여 방법", "subtitle": "무양념 닭고기만 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "chicken_breast", "food_ko": "닭가슴살", "safety": "safe",
            "cover_file": "",
            "cover_title": "CHICKEN BREAST",
            "body1": {"title": "먹어도 돼요!", "subtitle": "고단백 저지방, 최고의 간식"},
            "body2": {"title": "급여 방법", "subtitle": "삶아서 무양념, 체중의 10% 이내"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "raspberry", "food_ko": "라즈베리", "safety": "safe",
            "cover_file": "cover_152_라즈베리_raspberry.png",
            "cover_title": "RASPBERRY",
            "body1": {"title": "먹어도 돼요!", "subtitle": "항산화, 식이섬유 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "소형견 2~3개, 대형견 5~6개"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "cranberry", "food_ko": "크랜베리", "safety": "safe",
            "cover_file": "",
            "cover_title": "CRANBERRY",
            "body1": {"title": "먹어도 돼요!", "subtitle": "비뇨기 건강, 항산화 효과"},
            "body2": {"title": "급여 방법", "subtitle": "무가당만 소량, 주스 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "coconut", "food_ko": "코코넛", "safety": "safe",
            "cover_file": "cover_154_코코넛_coconut.png",
            "cover_title": "COCONUT",
            "body1": {"title": "먹어도 돼요!", "subtitle": "중쇄지방산, 피모 건강"},
            "body2": {"title": "급여 방법", "subtitle": "과육 소량, 코코넛 오일 1티스푼"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "white_fish", "food_ko": "흰살생선", "safety": "safe",
            "cover_file": "",
            "cover_title": "WHITE FISH",
            "body1": {"title": "먹어도 돼요!", "subtitle": "고단백 저지방, 오메가3 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "뼈 제거, 익혀서 무양념 급여"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "lettuce", "food_ko": "상추", "safety": "safe",
            "cover_file": "cover_160_상추_lettuce.png",
            "cover_title": "LETTUCE",
            "body1": {"title": "먹어도 돼요!", "subtitle": "수분+식이섬유, 저칼로리"},
            "body2": {"title": "급여 방법", "subtitle": "씻어서 생으로 2~3장"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "green_beans", "food_ko": "강낭콩", "safety": "safe",
            "cover_file": "",
            "cover_title": "GREEN BEANS",
            "body1": {"title": "먹어도 돼요!", "subtitle": "식이섬유+비타민K 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "반드시 익혀서, 소량 급여"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "bell_pepper", "food_ko": "파프리카", "safety": "safe",
            "cover_file": "",
            "cover_title": "BELL PEPPER",
            "body1": {"title": "먹어도 돼요!", "subtitle": "비타민C 풍부, 항산화 효과"},
            "body2": {"title": "급여 방법", "subtitle": "씨 제거, 소량 생/익혀서"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "asparagus", "food_ko": "아스파라거스", "safety": "safe",
            "folder": "170_asparagus_아스파라거스",
            "cover_file": "cover_161_아스파라거스_asparagus.png",
            "cover_title": "ASPARAGUS",
            "body1": {"title": "먹어도 돼요!", "subtitle": "엽산+비타민K, 해독 효과"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 잘게 잘라 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "beet", "food_ko": "비트", "safety": "safe",
            "folder": "176_beet_비트",
            "cover_file": "cover_166_비트_beet.png",
            "cover_title": "BEET",
            "body1": {"title": "먹어도 돼요!", "subtitle": "항산화+철분, 혈액 건강"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 소량, 소변 붉어질 수 있음"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "napa_cabbage", "food_ko": "배추", "safety": "safe",
            "cover_file": "",
            "cover_title": "NAPA CABBAGE",
            "body1": {"title": "먹어도 돼요!", "subtitle": "식이섬유+비타민C, 저칼로리"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 소량, 과다 시 가스"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "radish", "food_ko": "무", "safety": "safe",
            "cover_file": "",
            "cover_title": "RADISH",
            "body1": {"title": "먹어도 돼요!", "subtitle": "소화 효소, 비타민C 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 소량, 생무 자극 주의"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "corn", "food_ko": "옥수수", "safety": "safe",
            "cover_file": "",
            "cover_title": "CORN",
            "body1": {"title": "먹어도 돼요!", "subtitle": "탄수화물+식이섬유 에너지원"},
            "body2": {"title": "급여 방법", "subtitle": "옥수수대 금지, 알갱이만 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "peas", "food_ko": "완두콩", "safety": "safe",
            "folder": "172_peas_완두콩",
            "cover_file": "cover_164_완두콩_peas.png",
            "cover_title": "PEAS",
            "body1": {"title": "먹어도 돼요!", "subtitle": "단백질+비타민, 다이어트 간식"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 소량, 껍질째 OK"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "pork", "food_ko": "돼지고기", "safety": "safe",
            "cover_file": "",
            "cover_title": "PORK",
            "body1": {"title": "먹어도 돼요!", "subtitle": "고단백, 비타민B1 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "완전히 익혀서, 기름 제거"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "turkey", "food_ko": "칠면조", "safety": "safe",
            "cover_file": "",
            "cover_title": "TURKEY",
            "body1": {"title": "먹어도 돼요!", "subtitle": "저지방 고단백, 알레르기 적음"},
            "body2": {"title": "급여 방법", "subtitle": "뼈 제거, 익혀서 무양념"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "lamb", "food_ko": "양고기", "safety": "safe",
            "cover_file": "",
            "cover_title": "LAMB",
            "body1": {"title": "먹어도 돼요!", "subtitle": "고단백+철분, 알레르기 적음"},
            "body2": {"title": "급여 방법", "subtitle": "기름 제거, 익혀서 소량"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "venison", "food_ko": "사슴고기", "safety": "safe",
            "cover_file": "",
            "cover_title": "VENISON",
            "body1": {"title": "먹어도 돼요!", "subtitle": "저지방 고단백, 알레르기 최적"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 무양념, 간식/토퍼로"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "rabbit", "food_ko": "토끼고기", "safety": "safe",
            "cover_file": "",
            "cover_title": "RABBIT",
            "body1": {"title": "먹어도 돼요!", "subtitle": "초저지방 고단백, 알레르기 최적"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 무양념, 뼈 제거"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "chicken_liver", "food_ko": "닭간", "safety": "safe",
            "cover_file": "",
            "cover_title": "CHICKEN LIVER",
            "body1": {"title": "먹어도 돼요!", "subtitle": "비타민A+철분, 영양 보충"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 주 2~3회, 과다 금지"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "beef_liver", "food_ko": "소간", "safety": "safe",
            "cover_file": "",
            "cover_title": "BEEF LIVER",
            "body1": {"title": "먹어도 돼요!", "subtitle": "비타민A+B12, 영양 최고"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 소량, 비타민A 과다 주의"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "heart", "food_ko": "심장(소/닭)", "safety": "safe",
            "cover_file": "",
            "cover_title": "HEART",
            "body1": {"title": "먹어도 돼요!", "subtitle": "타우린+CoQ10, 심장 건강"},
            "body2": {"title": "급여 방법", "subtitle": "익혀서 잘게, 주 2~3회"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "tripe", "food_ko": "양(위장)", "safety": "safe",
            "cover_file": "",
            "cover_title": "TRIPE",
            "body1": {"title": "먹어도 돼요!", "subtitle": "프로바이오틱스, 소화 촉진"},
            "body2": {"title": "급여 방법", "subtitle": "녹색 트라이프 추천, 익혀서"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "bone_broth", "food_ko": "사골국물", "safety": "safe",
            "cover_file": "",
            "cover_title": "BONE BROTH",
            "body1": {"title": "먹어도 돼요!", "subtitle": "관절 건강, 콜라겐 풍부"},
            "body2": {"title": "급여 방법", "subtitle": "무양념으로 끓여서, 식혀서 급여"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
        {
            "food_id": "cod", "food_ko": "대구", "safety": "safe",
            "cover_file": "",
            "cover_title": "COD",
            "body1": {"title": "먹어도 돼요!", "subtitle": "저지방 고단백, 오메가3"},
            "body2": {"title": "급여 방법", "subtitle": "뼈 제거, 익혀서 무양념"},
            "cta": {"title": "저장 & 공유", "subtitle": "주변 견주에게 알려주세요!"},
        },
    ],
}


# ============================================================
# 배치 실행
# ============================================================
def run_batch(batch_name):
    items = ITEMS.get(batch_name)
    if not items:
        print(f"[ERROR] 알 수 없는 배치: {batch_name}")
        print(f"사용 가능: {', '.join(ITEMS.keys())}")
        sys.exit(1)

    print("=" * 70)
    print(f"WO-2026-0205-004 배치: {batch_name.upper()} ({len(items)}건)")
    print("=" * 70)

    results = []
    success = 0
    skip = 0

    for i, item in enumerate(items, 1):
        fid = item["food_id"]
        fko = item["food_ko"]
        print(f"\n[{i}/{len(items)}] {fid} ({fko}) — {item['safety'].upper()}")

        r = process_item(item)
        results.append(r)

        if r["skipped"]:
            skip += 1
            print(f"  → SKIP: {'; '.join(r['errors'])}")
        elif r["errors"]:
            print(f"  → PARTIAL: {'; '.join(r['errors'])}")
            success += 1  # 부분 성공도 카운트
        else:
            success += 1
            print(f"  → OK")

    # 보고서 출력
    print(f"\n{'=' * 70}")
    print(f"[B그룹 배치 {batch_name.upper()} 완료 보고]")
    print(f"{'=' * 70}")
    print(f"배치: {batch_name.upper()}")
    print(f"실행 일시: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"총 처리: {success}건 / {len(items)}건 (스킵: {skip}건)")
    print()
    print(f"{'#':<3} {'영문명':<20} {'text.json':<10} {'렌더링':<10} {'캡션':<10} {'validators':<12} {'시트전환':<10} {'비고':<20}")
    print("-" * 100)

    for i, r in enumerate(results, 1):
        tj = "O" if r["text_json"] else "X"
        rend = f"{'O' if r['render_01'] else 'X'}{'O' if r['render_02'] else 'X'}{'O' if r['render_03'] else 'X'}"
        cap = f"{'O' if r['caption_insta'] else 'X'}{'O' if r['caption_threads'] else 'X'}"
        val = r["validators"]
        sheet = "body_ready" if not r["skipped"] and not r["errors"] else ("SKIP" if r["skipped"] else "PARTIAL")
        note = "; ".join(r["errors"])[:20] if r["errors"] else ""
        print(f"{i:<3} {r['food_id']:<20} {tj:<10} {rend:<10} {cap:<10} {val:<12} {sheet:<10} {note:<20}")

    # 실패 상세
    failed = [r for r in results if r["errors"]]
    if failed:
        print(f"\n실패 건:")
        for r in failed:
            print(f"  - {r['food_id']}: {'; '.join(r['errors'])}")

    # JSON 보고서 저장
    report = {
        "work_order": "WO-2026-0205-004",
        "batch": batch_name.upper(),
        "executed_at": datetime.now().isoformat(),
        "total": len(items),
        "success": success,
        "skipped": skip,
        "results": results,
    }
    report_path = PROJECT_ROOT / "config" / "data" / f"wo_004_batch_{batch_name}.json"
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    print(f"\n보고서: {report_path}")

    return results


# ============================================================
# main
# ============================================================
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("사용법: python wo_004_batch.py <forbidden|danger|caution|safe|all>")
        sys.exit(1)

    batch = sys.argv[1].lower()

    if batch == "all":
        for b in ["forbidden", "danger", "caution", "safe"]:
            run_batch(b)
    else:
        run_batch(batch)
