#!/usr/bin/env python3
"""
배치 콘텐츠 생성기 - 모든 커버에 대해 콘텐츠 생성
v9.1 규칙 준수: Arial Black 114px, top 150px, 85% 세이프존
"""

import os
import re
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# 경로 설정
BASE_DIR = Path("/Users/al02399300/Desktop/Jun_AI/Dog_Contents/project_sunshine")
COVER_DIR = BASE_DIR / "content/images/000_cover/02_ready"
CONTENT_DIR = BASE_DIR / "content/images"

# 폰트 설정
ARIAL_BLACK = "/Library/Fonts/Arial Black.ttf"
FONT_SIZE = 114
TOP_Y = 150
MIN_FONT = 80

def get_font(path, size):
    try:
        return ImageFont.truetype(path, size)
    except:
        return ImageFont.load_default()

def add_text_with_shadow(draw, pos, text, font, fill):
    """v9 그림자 스펙"""
    x, y = pos
    for offset in range(1, 8):
        alpha = int(180 * (1 - offset/8))
        draw.text((x, y + 4 + offset), text, font=font, fill=(0, 0, 0, alpha))
    draw.text(pos, text, font=font, fill=fill)

def apply_cover_text(input_path, output_path, title):
    """v9.1 텍스트 오버레이"""
    img = Image.open(input_path).convert("RGBA")

    if img.size != (1080, 1080):
        img = img.resize((1080, 1080), Image.LANCZOS)

    width, height = img.size
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    font_size = FONT_SIZE
    max_width = width * 0.85

    while font_size >= MIN_FONT:
        font_title = get_font(ARIAL_BLACK, font_size)
        title_bbox = draw.textbbox((0, 0), title, font=font_title)
        title_w = title_bbox[2] - title_bbox[0]
        if title_w <= max_width:
            break
        font_size -= 10

    title_x = (width - title_w) // 2
    add_text_with_shadow(draw, (title_x, TOP_Y), title, font_title, (255, 255, 255, 255))

    result = Image.alpha_composite(img, overlay)
    result.convert("RGB").save(output_path, quality=95)

    return font_size

def parse_cover_filename(filename):
    """커버 파일명 파싱: cover_{num}_{korean}_{english}.png"""
    match = re.match(r'cover_(\d+)_([^_]+)_(.+?)(?:_DANGER)?(?:\d*)\.png', filename)
    if match:
        return {
            'num': int(match.group(1)),
            'korean': match.group(2),
            'english': match.group(3).replace('_DANGER', '').rstrip('0123456789'),
            'is_danger': 'DANGER' in filename
        }
    return None

def get_existing_content_folders():
    """기존 콘텐츠 폴더 목록"""
    existing = set()
    for folder in CONTENT_DIR.iterdir():
        if folder.is_dir() and folder.name != '000_cover':
            # 폴더명에서 영문명 추출
            match = re.match(r'\d+_([a-z_]+)', folder.name)
            if match:
                existing.add(match.group(1).rstrip('_'))
    return existing

def generate_caption_instagram(topic_kr, topic_en, is_danger=False):
    """인스타그램 캡션 생성"""
    if is_danger:
        return f"""🚫 {topic_kr}, 강아지가 먹으면 안 돼요!

우리 댕댕이한테 {topic_kr}은(는) 위험해요 ⚠️

❌ 절대 주지 마세요
❌ 실수로 먹었다면 즉시 병원으로!

📌 저장해두고 가족들과 공유하세요!

💬 우리 집 댕댕이 이름은?
댓글로 알려주세요! 🐾

#강아지 #반려견 #강아지음식 #강아지간식 #댕댕이 #골든리트리버 #햇살이 #{topic_en} #{topic_kr} #강아지금지음식 #펫스타그램 #멍스타그램

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI."""
    else:
        return f"""✅ {topic_kr}, 강아지가 먹어도 돼요!

11살 햇살이도 좋아하는 {topic_kr}! 🐕

✨ 급여 시 주의사항
- 적당량만 급여하세요
- 처음엔 소량으로 시작
- 알레르기 반응 확인

📌 저장해두고 나중에 참고하세요!

💬 우리 댕댕이가 좋아하는 음식은?
댓글로 알려주세요! 🐾

#강아지 #반려견 #강아지음식 #강아지간식 #댕댕이 #골든리트리버 #햇살이 #{topic_en} #{topic_kr} #펫스타그램 #멍스타그램

ℹ️ 일부 이미지는 AI로 생성되었습니다.
ℹ️ Some images were generated by AI."""

def generate_caption_threads(topic_kr, topic_en, is_danger=False):
    """쓰레드 캡션 생성"""
    if is_danger:
        return f"""🚫 {topic_kr} - 강아지 금지 음식!

절대 주지 마세요 ⚠️

#강아지 #{topic_kr} #반려견"""
    else:
        return f"""✅ {topic_kr} - 강아지가 먹어도 OK!

적당량 급여하세요 🐕

#강아지 #{topic_kr} #반려견"""

def create_content(cover_info, cover_path):
    """콘텐츠 폴더 생성 및 파일 생성"""
    num = cover_info['num']
    korean = cover_info['korean']
    english = cover_info['english']
    is_danger = cover_info['is_danger']

    # 폴더명 결정
    folder_name = f"{num:03d}_{english}_{korean}"
    content_folder = CONTENT_DIR / folder_name

    # 이미 존재하면 스킵
    if content_folder.exists():
        return None, "이미 존재"

    # 폴더 생성
    content_folder.mkdir(parents=True, exist_ok=True)

    # 커버 이미지 복사 및 텍스트 오버레이
    output_cover = content_folder / f"{english}_00.png"
    title = english.upper().replace('_', ' ')
    font_size = apply_cover_text(cover_path, output_cover, title)

    # 캡션 생성
    caption_insta = content_folder / "caption_instagram.txt"
    caption_threads = content_folder / "caption_threads.txt"

    caption_insta.write_text(generate_caption_instagram(korean, english, is_danger), encoding='utf-8')
    caption_threads.write_text(generate_caption_threads(korean, english, is_danger), encoding='utf-8')

    return folder_name, f"생성완료 ({font_size}px)"

def main():
    print("=" * 60)
    print("🎨 김영현 과장입니다. 배치 콘텐츠 생성을 시작합니다.")
    print("=" * 60)

    # 커버 파일 목록
    covers = list(COVER_DIR.glob("cover_*.png"))
    print(f"\n📁 총 {len(covers)}개 커버 발견")

    created = []
    skipped = []
    errors = []

    for cover_path in sorted(covers):
        info = parse_cover_filename(cover_path.name)
        if not info:
            errors.append((cover_path.name, "파일명 파싱 실패"))
            continue

        try:
            folder, status = create_content(info, cover_path)
            if folder:
                created.append((folder, status))
                print(f"  ✅ {folder} - {status}")
            else:
                skipped.append((cover_path.name, status))
        except Exception as e:
            errors.append((cover_path.name, str(e)))
            print(f"  ❌ {cover_path.name} - {e}")

    print("\n" + "=" * 60)
    print("📊 결과 요약")
    print("=" * 60)
    print(f"  생성: {len(created)}개")
    print(f"  스킵: {len(skipped)}개 (이미 존재)")
    print(f"  오류: {len(errors)}개")

    if created:
        print(f"\n✅ 생성된 콘텐츠 ({len(created)}개):")
        for folder, status in created[:20]:  # 처음 20개만 출력
            print(f"    - {folder}")
        if len(created) > 20:
            print(f"    ... 외 {len(created) - 20}개")

    if errors:
        print(f"\n❌ 오류 ({len(errors)}개):")
        for name, err in errors:
            print(f"    - {name}: {err}")

    return created, skipped, errors

if __name__ == "__main__":
    main()
